version: "3.8"

services:
  app:
    build: .
    ports:
      - "3000:80"
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: mydatabase
    ports:
    - "27017:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  nginx:
    image: nginx:1.13.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - app:/usr/share/nginx/html
    depends_on:
      - app

volumes:
  app:
